// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEx01umG-xMrmH2ckGjmiYUBvNis-AWus',
    appId: '1:707771328699:web:eb0b74e8800ae5d78b619e',
    messagingSenderId: '707771328699',
    projectId: 'coffee-help',
    authDomain: 'coffee-help.firebaseapp.com',
    storageBucket: 'coffee-help.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDerW4lDnD1VYsT9tHoJe0KHHTJgmPH5xI',
    appId: '1:707771328699:android:b289dcc4d9d5aa578b619e',
    messagingSenderId: '707771328699',
    projectId: 'coffee-help',
    storageBucket: 'coffee-help.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIddnVZgHaA_2shXjUquC0hCQtTDn8I4',
    appId: '1:707771328699:ios:cf9d317f929da8c18b619e',
    messagingSenderId: '707771328699',
    projectId: 'coffee-help',
    storageBucket: 'coffee-help.appspot.com',
    iosClientId: '707771328699-si9csg77qbtfp9q3qf2f984i38rall11.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIddnVZgHaA_2shXjUquC0hCQtTDn8I4',
    appId: '1:707771328699:ios:cf9d317f929da8c18b619e',
    messagingSenderId: '707771328699',
    projectId: 'coffee-help',
    storageBucket: 'coffee-help.appspot.com',
    iosClientId: '707771328699-si9csg77qbtfp9q3qf2f984i38rall11.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeHelp',
  );
}
